# This file contains templated variables to avoid repeating the same hard-coded values.
# Templated variables are denoted by the dollar curly braces token. The following details each templated variable that you can use:
# `starter_location`: This is an Azure location sourced from the `starter_location` variable. This can be used to set the location of resources.
# `default_postfix`: This is a string sourced from the variable `default_postfix`. This can be used to append to resource names for consistency.
# `root_parent_management_group_id`: This is the id of the management group that the ALZ hierarchy will be nested under.
# `subscription_id_identity`: The subscription ID of the subscription to deploy the identity resources to, sourced from the variable `subscription_id_identity`.
# `subscription_id_connectivity`: The subscription ID of the subscription to deploy the connectivity resources to, sourced from the variable `subscription_id_connectivity`.
# `subscription_id_management`: The subscription ID of the subscription to deploy the management resources to, sourced from the variable `subscription_id_management`.
---
archetypes: # `caf-enterprise-scale` module, add inputs as listed on the module registry where necessary.
  # Base variables
  root_name: ANU
  root_id: anu
  subscription_id_connectivity: ${subscription_id_connectivity}
  subscription_id_identity: ${subscription_id_identity}
  subscription_id_management: ${subscription_id_management}
  root_parent_id: ${root_parent_management_group_id}
  deploy_core_landing_zones: true
  deploy_corp_landing_zones: true
  deploy_online_landing_zones: true
  default_location: ${starter_location}
  deploy_management_resources: true
  deploy_connectivity_resources: true
  deploy_identity_resources: true
  disable_telemetry: true

  # Management
  configure_management_resources:
    location: ${starter_location}
    settings:
      log_analytics:
        enabled: true
        config:
          retention_in_days: 30
          enable_monitoring_for_vm: true
          enable_monitoring_for_vmss: true
          enable_solution_for_agent_health_assessment: true
          enable_solution_for_anti_malware: true
          enable_solution_for_change_tracking: true
          enable_solution_for_service_map: true
          enable_solution_for_sql_assessment: true
          enable_solution_for_sql_vulnerability_assessment: true
          enable_solution_for_sql_advanced_threat_detection: true
          enable_solution_for_updates: true
          enable_solution_for_vm_insights: true
          enable_solution_for_container_insights: true
          enable_sentinel: false
      security_center:
        enabled: true
        config:
          email_security_contact: "ajajayakumar@microsoft.com, ajayjayakumaraj@outlook.com" #change to it.security@anu.edu.au, windows.co.its@anu.edu.au
          enable_defender_for_apis: false
          enable_defender_for_app_services: false
          enable_defender_for_arm: false
          enable_defender_for_containers: false
          enable_defender_for_cosmosdbs: false
          enable_defender_for_cspm: false
          enable_defender_for_dns: false
          enable_defender_for_key_vault: true
          enable_defender_for_oss_databases: false
          enable_defender_for_servers: true
          enable_defender_for_servers_vulnerability_assessments: false
          enable_defender_for_sql_servers: false
          enable_defender_for_sql_server_vms: false
          enable_defender_for_storage: false
      location: ${starter_location}
      tags: null
    advanced:
      asc_export_resource_group_name: rg-asc-export
      custom_settings_by_resource_type:
        azurerm_resource_group:
          management:
            name: rg-mgmt-prod-001
        azurerm_log_analytics_workspace:
          management:
            name: la-mgmt-prod-001
        azurerm_automation_account:
          management:
            name: aa-mgmt-prod-001

  # Networking
  configure_connectivity_resources:
    settings:
      hub_networks:
        - config:
            address_space:
              - 10.18.0.0/22
            location: ${starter_location}
            link_to_ddos_protection_plan: false
            dns_servers: []
            bgp_community: "" #to change
            subnets: []
            virtual_network_gateway:
              enabled: true
              config:
                address_prefix: 10.18.1.0/27
                gateway_sku_expressroute: ErGw1AZ
                gateway_sku_vpn: VpnGw2AZ
              advanced_vpn_settings:
                enable_bgp: null #change
                active_active: null
                private_ip_address_allocation: ""
                default_local_network_gateway_id: ""
                vpn_client_configuration: []
                bgp_settings: []
                custom_route: []
            azure_firewall:
              enabled: false
              config:
                address_prefix: 10.18.2.0/25
                enable_dns_proxy: true
                sku_tier: "Standard"
                base_policy_id: ""
                private_ip_ranges: []
                threat_intelligence_mode: "Deny" #to check if can be changed to Alert or Off
                threat_intelligence_allowlist: {}
                availability_zones:
                  zone_1: true
                  zone_2: true
                  zone_3: true
            spoke_virtual_network_resource_ids: [] #To be provided to test connectivity
            enable_outbound_virtual_network_peering: true
            enable_hub_network_mesh_peering: false
      vwan_hub_networks: []
      ddos_protection_plan:
        enabled: false
        config:
          location: ${starter_location}
      dns:
        enabled: false
        config:
          location: null
          enable_private_link_by_service:
            azure_api_management: true
            azure_app_configuration_stores: true
            azure_arc: true
            azure_automation_dscandhybridworker: true
            azure_automation_webhook: true
            azure_backup: true
            azure_batch_account: true
            azure_bot_service_bot: true
            azure_bot_service_token: true
            azure_cache_for_redis: true
            azure_cache_for_redis_enterprise: true
            azure_container_registry: true
            azure_cosmos_db_cassandra: true
            azure_cosmos_db_gremlin: true
            azure_cosmos_db_mongodb: true
            azure_cosmos_db_sql: true
            azure_cosmos_db_table: true
            azure_data_explorer: true
            azure_data_factory: true
            azure_data_factory_portal: true
            azure_data_health_data_services: true
            azure_data_lake_file_system_gen2: true
            azure_database_for_mariadb_server: true
            azure_database_for_mysql_server: true
            azure_database_for_postgresql_server: true
            azure_digital_twins: true
            azure_event_grid_domain: true
            azure_event_grid_topic: true
            azure_event_hubs_namespace: true
            azure_file_sync: true
            azure_hdinsights: true
            azure_iot_dps: true
            azure_iot_hub: true
            azure_key_vault: true
            azure_key_vault_managed_hsm: true
            azure_kubernetes_service_management: true
            azure_machine_learning_workspace: true
            azure_managed_disks: true
            azure_media_services: true
            azure_migrate: true
            azure_monitor: true
            azure_purview_account: true
            azure_purview_studio: true
            azure_relay_namespace: true
            azure_search_service: true
            azure_service_bus_namespace: true
            azure_site_recovery: true
            azure_sql_database_sqlserver: true
            azure_synapse_analytics_dev: true
            azure_synapse_analytics_sql: true
            azure_synapse_studio: true
            azure_web_apps_sites: true
            azure_web_apps_static_sites: true
            cognitive_services_account: true
            microsoft_power_bi: true
            signalr: true
            signalr_webpubsub: true
            storage_account_blob: true
      private_link_locations:
        - ${starter_location}
      public_dns_zones: []
      private_dns_zones: []
      enable_private_dns_zone_virtual_network_link_on_hubs: true
      enable_private_dns_zone_virtual_network_link_on_spokes: true
      virtual_network_resource_ids_to_link: []
    location: ${starter_location}
    tags: null
    advanced:
      custom_settings_by_resource_type:
        azurerm_resource_group:
          connectivity:
            ${starter_location}:
              name: rg-vnet-prod-001
          dns:
            ${starter_location}:
              name: rg-dns-prod-001
        azurerm_virtual_network:
          connectivity:
            ${starter_location}:
              name: vnet-hub-prod-001
        azurerm_virtual_network_gateway:
          connectivity_expressroute:
            ${starter_location}:
              name: vgw-er-prod-001
          connectivity_vpn:
            ${starter_location}:
              name: vgw-vpn-prod-001
        azurerm_firewall:
          connectivity:
            ${starter_location}:
              name: azfw-hub-prod-001
  # Identity
  configure_identity_resources:
    settings:
      identity:
        enabled: true
        config:
          enable_deny_public_ip: true
          enable_deny_rdp_from_internet: true
          enable_deny_subnet_without_nsg: true
          enable_deploy_azure_backup_on_vms: false
